import { useState, useEffect } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { ChevronRight, ChevronLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { formatCost } from "@/lib/formatters";

// Mock Data Generator
const generateMockLogs = (count: number) => {
    const models = ['gpt-4', 'gpt-3.5-turbo', 'claude-3-opus', 'gemini-1.5-pro', 'llama-3-70b'];
    const statuses = ['success', 'success', 'success', 'success', 'failed']; // 80% success
    const prompts = [
        "Explain quantum computing in simple terms",
        "Write a python function to Fibonacci sequence",
        "Translate 'Hello world' to French",
        "Summarize this article for me...",
        "Debug this React component error",
        "Generate a SQL query for user retention",
        "Create a travel itinerary for Japan",
        "Review this code for security vulnerabilities"
    ];

    return Array.from({ length: count }).map((_, i) => ({
        id: `req-${i}`,
        timestamp: new Date(Date.now() - Math.random() * 86400000 * 3).toISOString(), // Last 3 days
        status: statuses[Math.floor(Math.random() * statuses.length)],
        model: models[Math.floor(Math.random() * models.length)],
        request: prompts[Math.floor(Math.random() * prompts.length)],
        response: "Here is the response generated by the AI model based on your input...",
        totalTokens: Math.floor(Math.random() * 1000) + 50,
        cost: Math.random() * 0.05,
        duration: Math.floor(Math.random() * 5000) + 200 // 200ms - 5200ms
    })).sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
};

// --- CONFIGURATION ---
const USE_MOCK_DATA = false; // Sunum/Demo için TRUE yapın
// ---------------------

export default function Requests() {
    const [logs, setLogs] = useState<any[]>([]);

    // Pagination
    const [currentPage, setCurrentPage] = useState(1);
    const logsPerPage = 15;


    useEffect(() => {
        // --- MOCK DATA MODE ---
        if (USE_MOCK_DATA) {
            const mockData = generateMockLogs(50);
            setLogs(mockData);
            return;
        }

        // Fetch real data from backend
        const fetchLogs = async () => {
            try {
                const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:5000';
                const res = await fetch(`${API_BASE}/api/logs?limit=1000`);
                const json = await res.json();
                setLogs(json.logs || []);
            } catch (error) {
                console.error('Failed to fetch logs:', error);
                setLogs([]);
            }
        };
        fetchLogs();
    }, []);

    const indexOfLastLog = currentPage * logsPerPage;
    const indexOfFirstLog = indexOfLastLog - logsPerPage;
    const currentLogs = logs.slice(indexOfFirstLog, indexOfLastLog);
    const totalPages = Math.ceil(logs.length / logsPerPage);

    const handleNextPage = () => { if (currentPage < totalPages) setCurrentPage(prev => prev + 1); };
    const handlePrevPage = () => { if (currentPage > 1) setCurrentPage(prev => prev - 1); };

    return (
        <DashboardLayout isFullWidth={true}>
            <div className="flex flex-col h-[calc(100vh-80px)]">

                {/* Header (No Filters) */}
                <div className="flex-none border-b border-gray-200 dark:border-white/5 bg-white dark:bg-[#0B0E14] px-6 py-4">
                    <div className="flex items-center gap-4">
                        <h1 className="text-xl font-bold text-gray-900 dark:text-white tracking-tight">Requests</h1>
                        <div className="flex items-center gap-2 text-xs px-2 py-1 rounded-full bg-green-100 dark:bg-green-500/10 text-green-700 dark:text-green-400 border border-green-200 dark:border-green-500/20">
                            <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
                            Live
                        </div>
                    </div>
                </div>

                {/* Table */}
                <div className="flex-1 overflow-auto bg-white dark:bg-[#0B0E14]">
                    <table className="w-full text-left border-collapse">
                        <thead className="bg-gray-50/50 dark:bg-[#12141a] sticky top-0 z-10 text-[11px] font-semibold text-gray-500 dark:text-gray-500 uppercase tracking-wider border-b border-gray-200 dark:border-white/5 backdrop-blur-sm">
                            <tr>
                                <th className="px-6 py-3 w-[180px]">Timestamp</th>
                                <th className="px-6 py-3 w-[100px]">Status</th>
                                <th className="px-6 py-3 max-w-[300px]">Input / Prompt</th>
                                <th className="px-6 py-3 max-w-[300px]">Output / Response</th>
                                <th className="px-6 py-3 w-[150px]">Model</th>
                                <th className="px-6 py-3 text-right w-[80px]">Tok</th>
                                <th className="px-6 py-3 text-right w-[80px]">Cost</th>
                                <th className="px-6 py-3 text-right w-[80px]">Lat</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100 dark:divide-white/[0.03] text-sm">
                            {currentLogs.map((log) => (
                                <tr
                                    key={log.id}
                                    className="hover:bg-gray-50 dark:hover:bg-white/[0.02] transition-colors group"
                                >
                                    <td className="px-6 py-3 whitespace-nowrap text-gray-600 dark:text-gray-400 font-mono text-xs">
                                        {new Date(log.timestamp).toLocaleString('en-US', { hour: 'numeric', minute: '2-digit', second: '2-digit', month: 'short', day: 'numeric' })}
                                    </td>
                                    <td className="px-6 py-3 whitespace-nowrap">
                                        <div className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wide border ${(log.status === 'success')
                                            ? 'bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-500/10 dark:text-emerald-400 dark:border-emerald-500/20'
                                            : 'bg-rose-50 text-rose-700 border-rose-200 dark:bg-rose-500/10 dark:text-rose-400 dark:border-rose-500/20'
                                            }`}>
                                            <div className={`w-1.5 h-1.5 rounded-full ${(log.status === 'success') ? 'bg-emerald-500' : 'bg-rose-500'}`} />
                                            {(log.status === 'success') ? '200 OK' : 'ERR'}
                                        </div>
                                    </td>
                                    <td className="px-6 py-3 text-gray-900 dark:text-gray-300 max-w-[300px] font-mono text-xs">
                                        <div className="truncate opacity-90">{log.prompt || log.request || 'N/A'}</div>
                                    </td>
                                    <td className="px-6 py-3 text-gray-600 dark:text-gray-400 max-w-[300px] font-mono text-xs">
                                        <div className="truncate opacity-80">{log.response || 'N/A'}</div>
                                    </td>
                                    <td className="px-6 py-3 whitespace-nowrap">
                                        <span className="text-xs font-medium text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-white/5 px-2 py-1 rounded border border-gray-200 dark:border-white/5">
                                            {log.model}
                                        </span>
                                    </td>
                                    <td className="px-6 py-3 text-right text-gray-600 dark:text-gray-400 font-mono text-xs">
                                        {log.totalTokens.toLocaleString()}
                                    </td>
                                    <td className="px-6 py-3 text-right text-gray-900 dark:text-gray-300 font-mono text-xs font-medium">
                                        {formatCost(log.cost || 0)}
                                    </td>
                                    <td className="px-6 py-3 text-right text-gray-600 dark:text-gray-400 font-mono text-xs">
                                        {(log.duration / 1000).toFixed(2)}s
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>

                {/* Footer */}
                <div className="flex-none border-t border-gray-200 dark:border-white/5 px-6 py-3 flex items-center justify-between bg-gray-50 dark:bg-[#0B0E14] text-xs text-gray-500">
                    <div>Showing {indexOfFirstLog + 1}-{Math.min(indexOfLastLog, logs.length)} of {logs.length} matches</div>
                    <div className="flex items-center gap-1">
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={handlePrevPage}
                            disabled={currentPage === 1}
                            className="h-7 w-7 p-0"
                        >
                            <ChevronLeft className="w-3 h-3" />
                        </Button>
                        <div className="px-2 font-mono">{currentPage} / {totalPages || 1}</div>
                        <Button
                            variant="outline"
                            size="sm"
                            onClick={handleNextPage}
                            disabled={currentPage >= totalPages}
                            className="h-7 w-7 p-0"
                        >
                            <ChevronRight className="w-3 h-3" />
                        </Button>
                    </div>
                </div>

            </div>
        </DashboardLayout>
    );
}
